name: Publish to npm registry

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish to npm registry
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          registry-url: 'https://registry.npmjs.org'
          always-auth : true

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
